export const LEVELS = [
    { id: 1, name: "VILA OCUPADA", operation: "LINHA DE FOGO", objective: "ROMPA A LINHA E DERRUBE O TANQUE ARGO", bossName: "ARGO MK-I", enemyHpScale: 1.00, enemyFireScale: 1.00, playerStartX: 2, checkpoints: [24, 48, 67], tint: "#c88a55", theme: "village" },
    { id: 2, name: "PONTE DE FERRO", operation: "AÇO PARTIDO", objective: "ATRAVESSE A PONTE E INTERCEPTE O TREM BLINDADO", bossName: "ARGO RAIL", enemyHpScale: 1.12, enemyFireScale: 0.94, playerStartX: 2, checkpoints: [22, 46, 69], tint: "#7d8890", theme: "bridge" },
    { id: 3, name: "SELVA MILITAR", operation: "FOLHA NEGRA", objective: "DESTRUA OS BUNKERS E LIMPE A ZONA AÉREA", bossName: "ARGO JUNGLE", enemyHpScale: 1.24, enemyFireScale: 0.89, playerStartX: 2, checkpoints: [20, 45, 66], tint: "#65764b", theme: "jungle" },
    { id: 4, name: "BASE INIMIGA", operation: "FERRO INTERNO", objective: "INVADA A BASE E DESATIVE A REDE DE DEFESA", bossName: "ARGO SIEGE", enemyHpScale: 1.36, enemyFireScale: 0.84, playerStartX: 2, checkpoints: [19, 43, 64], tint: "#5c6870", theme: "base" },
    { id: 5, name: "DESERTO VERMELHO", operation: "SOL DE CHUMBO", objective: "CRUZE AS DUNAS E DESTRUA O COMBOIO BLINDADO", bossName: "ARGO SANDSTORM", enemyHpScale: 1.48, enemyFireScale: 0.80, playerStartX: 2, checkpoints: [20, 44, 65], tint: "#b07843", theme: "desert" },
    { id: 6, name: "PORTO DE GUERRA", operation: "MARÉ DE AÇO", objective: "TOME O CAIS E AFUNDE A PLATAFORMA DE ARTILHARIA", bossName: "ARGO HARBOR", enemyHpScale: 1.60, enemyFireScale: 0.76, playerStartX: 2, checkpoints: [19, 42, 64], tint: "#426678", theme: "harbor" },
    { id: 7, name: "CIDADE EM RUÍNAS", operation: "CINZAS VIVAS", objective: "AVANCE PELOS ESCOMBROS E DERRUBE O COLOSSO URBANO", bossName: "ARGO COLOSSUS", enemyHpScale: 1.74, enemyFireScale: 0.73, playerStartX: 2, checkpoints: [18, 41, 63], tint: "#6d5d55", theme: "ruins" },
    { id: 8, name: "CÂNION DA MORTE", operation: "ECO DE PÓLVORA", objective: "ROMPA AS EMBOSCADAS E DESTRUA A FORTALEZA MÓVEL", bossName: "ARGO CRAWLER", enemyHpScale: 1.88, enemyFireScale: 0.70, playerStartX: 2, checkpoints: [18, 40, 62], tint: "#9a6645", theme: "canyon" },
    { id: 9, name: "NEVE DE FERRO", operation: "INVERNO HOSTIL", objective: "INVADA O POSTO POLAR E NEUTRALIZE O CANHÃO DE GELO", bossName: "ARGO FROST", enemyHpScale: 2.02, enemyFireScale: 0.67, playerStartX: 2, checkpoints: [17, 39, 61], tint: "#7fa3ad", theme: "snow" },
    { id: 10, name: "FÁBRICA BÉLICA", operation: "LINHA DE MONTAGEM", objective: "SABOTE A PRODUÇÃO E DESTRUA O MECHA INDUSTRIAL", bossName: "ARGO FORGE", enemyHpScale: 2.18, enemyFireScale: 0.64, playerStartX: 2, checkpoints: [17, 38, 60], tint: "#70584c", theme: "factory" },
    { id: 11, name: "CÉU EM CHAMAS", operation: "ÚLTIMA ESQUADRILHA", objective: "INVADA O AERÓDROMO E DERRUBE A NAVE DE ASSALTO", bossName: "ARGO SKYFALL", enemyHpScale: 2.35, enemyFireScale: 0.61, playerStartX: 2, checkpoints: [16, 37, 59], tint: "#59657d", theme: "airfield" },
    { id: 12, name: "FORTALEZA OMEGA", operation: "ÚLTIMO IMPACTO", objective: "ROMPA A FORTALEZA E DESTRUA O NÚCLEO DE GUERRA", bossName: "ARGO OMEGA", enemyHpScale: 2.55, enemyFireScale: 0.58, playerStartX: 2, checkpoints: [16, 36, 58], tint: "#805046", theme: "fortress" },
];
export const getLevel = (id) => LEVELS.find((l) => l.id === id) ?? LEVELS[0];
